services:
  - type: web
    name: app-cbi-server
    env: node
    region: oregon
    rootDir: server
    buildCommand: npm install -g pnpm && cd /opt/render/project/src && pnpm install --filter=server && pnpm --filter=server run build && pnpm --filter=server exec prisma generate
    startCommand: cd /opt/render/project/src/server && pnpm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: TOKEN_SECRET
        sync: false
      - key: PORT
        value: 3000
