services:
  - type: web
    name: app-cbi-server
    env: node
    region: oregon
    buildCommand: cd server && npm install -g pnpm && pnpm install && pnpm run build && pnpm exec prisma generate
    startCommand: cd server && pnpm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: TOKEN_SECRET
        sync: false
      - key: PORT
        value: 3000
