services:
  - type: web
    name: app-cbi-server
    env: node
    region: oregon
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: TOKEN_SECRET
        sync: false
      - key: PORT
        value: 3000
